version: '3.4'
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db/data_dump:/var/lib/mysql
    healthcheck:
      test: "exit 0"
    environment:
      - MYSQL_DATABASE=db_app
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=maria
      - MYSQL_PASSWORD=pass

  keycloak:
    image: jboss/keycloak:latest
    hostname: keycloak
    command:
      - " -b 0.0.0.0"
    container_name: "keycloak"
    healthcheck:
      test: "exit 0"
    volumes:
      - ./keycloak/imports:/opt/jboss/keycloak/imports
      - ./keycloak/exports:/opt/jboss/keycloak/exports
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/demo-realm.json -Dkeycloak.profile.feature.upload_scripts=enabled
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: MYSQL
      DB_ADDR: db
      DB_DATABASE: db_app
      DB_PORT: 3306
      DB_USER: maria
      DB_PASSWORD: pass
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: pass
    ports:
      - 80:8080
    links:
      - "db:db"
    depends_on:
      - db